### ISSUE TITLE
5.1: SapphireTestState config forces you to prefer-source for development/testing

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-staticpublishqueue#138]
A new configuration has been added in `5.1`.

```yml
  SilverStripe\Dev\State\SapphireTestState:
    properties:
      States:
        staticPublisherState: '%$SilverStripe\StaticPublishQueue\Dev\StaticPublisherState'
```

```php
public function setUp(SapphireTest $test)
{
    // Prepare queued jobs related functionality for unit test run
    // Disable queue logging
    Injector::inst()->registerService(new QueuedJobsTest_Handler(), QueuedJobHandler::class);

    // Disable special actions of the queue service
    Config::modify()->set(QueuedJobService::class, 'use_shutdown_function', false);

    // It seems Injector doesn't cover all cases so we force-inject a test service which is suitable for unit tests
    Injector::inst()->registerService(new QueuedJobsTestService(), QueuedJobService::class);
    SiteTreePublishingEngine::setQueueService(QueuedJobService::singleton());
}
```

`QueuedJobsTest_Handler` is a `test` class from the QueuedJobs module, and `QueuedJobsTestService` is a `test` class from this module. This means they're not available unless you `composer install --prefer-source`.

Is this the expected behaviour?
