### ISSUE TITLE
Allow StaticPublishingTrigger to be added in DataExtensions

### ISSUE THREAD

**Issue by tiller1010** [silverstripe/silverstripe-staticpublishqueue#211]
### Description

I would like to add StaticPublishingTrigger to a DataObject through a DataExtension, but [StaticPublishingTrigger checks if the original DataObject implements StaticPublishingTrigger](https://github.com/silverstripe/silverstripe-staticpublishqueue/blob/6/src/Extension/Engine/SiteTreePublishingEngine.php#L282).

```php
// I want the Resource DataObject to queue an update to its own URL when changed.
class ResourceExtension extends DataExtension implements StaticallyPublishable, StaticPublishingTrigger
{
  public function urlsToCache()
  {
    return [$this->owner->getDetailPageAbsoluteLink() => 0];
  }

  public function objectsToUpdate($context)
  {
    return $this->owner;
  }
}
```

What if there was a loop over extensions that checked for this interface?
```php
$extensionImplementsInterface = false;
foreach ($siteTree->get_extensions() as $extension) {
    if (new $extension instanceof StaticPublishingTrigger) {
        $extensionImplementsInterface = true;
        break;
    }
}

// The page does not include the required extension, and it doesn't implement a Trigger
if (!$siteTree->hasExtension(PublishableSiteTree::class) && !($siteTree instanceof StaticPublishingTrigger) && !$extensionImplementsInterface) {
    return;
}
```

### Additional context or points of discussion
This is how I have the extensions applied
```yml
---
Name: add_static_publishing_methods_to_resource
---
VendorName\ResourcePackage\Resources\Resource:
  extensions:
    - App\Resources\ResourceExtension

---
Name: update_resource_detail_on_change
After: add_static_publishing_methods_to_resource
---
VendorName\ResourcePackage\Resources\Resource:
  extensions:
    - SilverStripe\StaticPublishQueue\Extension\Engine\SiteTreePublishingEngine
```

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

## PRs
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/214
